package app.terminalssh.secure.security

import android.os.Build
import com.jcraft.jsch.JSch
import com.jcraft.jsch.KeyPair
import java.io.ByteArrayOutputStream

/**
 * Generates an SSH key pair inside the app, so a user never has to move private-key
 * material through a file manager or a messaging app to get onto a server.
 *
 * The key is generated by JSch and handed straight to the vault; it is deliberately not
 * an AndroidKeyStore key, because SSH authentication needs the private scalar itself and
 * AndroidKeyStore keys are non-exportable by design.
 */
enum class KeyAlgorithm(val jschType: Int, val label: String) {
    /**
     * Preferred where available. JSch's Ed25519 generator lives in the jar's
     * `META-INF/versions/15/` tree, which Android's D8 does not unpack, and the platform
     * itself only gained EdDSA in API 33 — so this is not offered below that.
     */
    ED25519(KeyPair.ED25519, "ed25519"),

    /** Universally available on API 26+ and still a modern choice. */
    ECDSA_256(KeyPair.ECDSA, "ecdsa-p256"),

    /** Last resort for servers that reject anything newer. */
    RSA_3072(KeyPair.RSA, "rsa-3072"),
    ;

    companion object {
        private const val ED25519_MIN_SDK = 33

        /** Algorithms this device can actually generate, best first. */
        fun supported(sdkInt: Int = Build.VERSION.SDK_INT): List<KeyAlgorithm> =
            entries.filter { it != ED25519 || sdkInt >= ED25519_MIN_SDK }

        fun default(sdkInt: Int = Build.VERSION.SDK_INT): KeyAlgorithm = supported(sdkInt).first()
    }
}

/** A freshly generated pair: private bytes for the vault, public text for the server. */
class GeneratedKey(
    val privateKey: ByteArray,
    val publicKey: String,
    val algorithm: KeyAlgorithm,
) {
    /** Zeroes the private material. Always call this once the key is in the vault. */
    fun wipe() = privateKey.fill(0)
}

object KeyGeneration {

    private const val RSA_BITS = 3072
    private const val ECDSA_BITS = 256

    /**
     * @param comment appended to the public key, the way `ssh-keygen -C` does; it is what
     *   identifies the line in an `authorized_keys` file later.
     * @throws IllegalArgumentException if [algorithm] is not supported on this device.
     */
    fun generate(algorithm: KeyAlgorithm, comment: String): GeneratedKey {
        require(algorithm in KeyAlgorithm.supported()) { "unsupported algorithm on this device" }

        val keySize = when (algorithm) {
            KeyAlgorithm.RSA_3072 -> RSA_BITS
            KeyAlgorithm.ECDSA_256 -> ECDSA_BITS
            KeyAlgorithm.ED25519 -> 0 // Fixed-size curve; JSch ignores the parameter.
        }

        val pair = KeyPair.genKeyPair(JSch(), algorithm.jschType, keySize)
        try {
            val privateOut = ByteArrayOutputStream()
            val publicOut = ByteArrayOutputStream()
            pair.writePrivateKey(privateOut)
            pair.writePublicKey(publicOut, comment)
            return GeneratedKey(
                privateKey = privateOut.toByteArray(),
                publicKey = publicOut.toString(Charsets.UTF_8.name()).trim(),
                algorithm = algorithm,
            )
        } finally {
            // Drops JSch's own copy of the private material.
            pair.dispose()
        }
    }
}
